;;; -*- Mode: LISP; Syntax: Common-Lisp; Package: COMPARE; Base: 10 -*-
;;;
;;; Source: compare-format.lisp	Module: compare		Status:	operational
;;;
;;; History:	Please record your edits in "compare-history.text".
;;;
;;; Purpose:	Provide the Sequence Comparison Utility with Formating Support.
;;;
;;; Usage:	This file is intended to be portable
;;;		to any COMMON LISP Environment.
;;;
;;; Compile:	Cf. "compare:compare;compare.lisp"
;;;
;;; Contents:
;;;
;;;	This file provides support for the various Output Formatters.
;;;
;;; NOTE!  Please consult "compare-face.lisp" for definition of the higher
;;;	   level interfaces visible to Users.
;;;
;;; Local Interfaces (generated by WRAP-PURE-STRING, below:)
;;;
;;;	pure-less		minimum-length
;;;	pure-greater		minimum-length
;;;	pure-equal		minimum-length
;;;	pure-minus		minimum-length
;;;	pure-space		minimum-length
;;;
;;; Local Interfaces:
;;;
;;;	wrap-pure-string	function-name char &optional
;;;				variable-name char-name
;;;
;;;	compare-formatter	differ-p a-sequence b-sequence
;;;				&key format &allow-other-keys
;;;
;;;	visible-p		header-type record
;;;
;;;	header-p		header-type record
;;;
;;;	initial-header		header-type-pair sequence-pair
;;;
;;;	find-header		header-type-pair sequence-pair interval-pair
;;;
;;;	diagnose-pair		differ-p sequence-pair
;;;
;;;	interval-to-string	interval
;;;
;;;	center-fill		center-sequence fill-count &optional fill-item
;;;				&key fill-minimum right-crop
;;;	center-values		center-length fill-count
;;;				&key fill-minimum right-crop
;;;
;;;	frame-records		records &key change-bar tab-spaces width
;;;	frame-record		record &key tab-spaces width
;;;	expand-tabs 		tabbed-string &key tab-spaces width
;;;
;;;	pure-string		minimum-length char &optional symbol
;;;

;;;
;;; Resume Module Context:
;;;
(in-package compare)

;;; No Requirements.
;;; No Shadows.
;;; No Unusual Packages.
;;; Nothing to Import.

;;;
;;; Dynamically Bound Interfaces:
;;;
(export '(*compare-formatter*
	   *default-compare-format*
	   *default-tab-spaces*))

;;;
;;; Macros:
;;;
(defmacro WRAP-PURE-STRING (function-name
			    char
			    &optional
			    (variable-name function-name)
			    (char-name nil char-name-sp))
  "Wrap Pure Character String Interfaces around their implementation."
  (let* ((char-doc (if char-name-sp char-name (char-name char)))
	 (variable-doc
	   (when char-doc
	     (format nil
		     "The maximum Read Only string consisting of ~As."
		     char-doc)))
	 (function-doc
	   (when char-doc
	     (format nil
		     "Get or Make a Read Only string consisting of ~As."
		     char-doc))))
    `(progn
       (defvar ,variable-name nil ,variable-doc)

       (defun ,function-name (minimum-length)
         ,function-doc
	 (pure-string minimum-length ,char ',variable-name))
       )))

;;;
;;; "Wrapped" Interfaces:
;;;
(wrap-pure-string PURE-LESS #\<)
(wrap-pure-string PURE-GREATER #\>)
(wrap-pure-string PURE-EQUAL #\=)
(wrap-pure-string PURE-MINUS #\-)
(wrap-pure-string PURE-SPACE #\Space)

;;;
;;; Special Variables and Constants:
;;;
(defparameter *COMPARE-FORMATTER* 'compare-formatter
  "The Standard Compare Formatter")

(defparameter *DEFAULT-COMPARE-FORMAT* :parallel
  "The Default Compare Format")

(defparameter *COMPARE-FRAMER* 'frame-record
  "The Standard Record Framer")

(defparameter *DEFAULT-TAB-SPACES*
	      (let ((space-cycle '(8)))
		;;
		;; The lexical expression: '#0=(8 . #0#)
		;; causes COMPILE to chase its tail...
		;;
		(setf (rest (last space-cycle)) space-cycle))
  "The Default (Relative) Tab Stops")

(defparameter *LABEL-FORMAT* " ~@{~@[~D ~]~}"
  "The Standard Label Format Directive String")

(defparameter *INTERVAL-FORMAT* "[~D~@[:~D~]]"
  "The Standard Interval Format Directive String")

;;;
;;; Now for the Code:
;;;
(defun COMPARE-FORMATTER (differ-p
                          a-sequence
                          b-sequence
                          &rest keys
                          &key
                          (format *default-compare-format*)
                          (width nil width-sp)
                          &allow-other-keys)
  "Dispatch to the appropriate Compare Formatter."
  (declare (special *default-compare-format*))
  (let ((selected-formatter (ccase format
			      (:delta #'compare-as-delta)
			      (:merge #'compare-and-merge)
			      (:parallel #'compare-in-parallel)
			      (:review #'compare-in-review)
			      (:series #'compare-in-series)
			      ))
        (formatter-keys keys))
    
    (unless (or (not width-sp)
                (and (integerp width)
                     (not (minusp width))))
      (cerror "Remove this keyword."
              "The ~S keyword specifies a ~A value: ~D."
              :width
              (if (integerp width) "negative" "non-integral")
              width)

      (setq formatter-keys (copy-list formatter-keys))
      (do ()
	  ((not (remf formatter-keys :width)))
        ;; Null Body.
        ))
    
    ;;
    ;; Pass control to the Compare Formatter interface selected here:
    ;;
    (apply selected-formatter differ-p a-sequence b-sequence formatter-keys)))

;;;
;;; Note that use of the Series Output Format :HEADER-TYPE-PAIR Keyword
;;; imposes the restriction that Records be implemented out of Strings.
;;;
;;; Type determinations are made with respect to the first character of
;;; these strings.
;;;
(defun VISIBLE-P (header-type record)
  "Is this record visible?"
  ;;
  ;; Null Records are treated as though they contain explicit
  ;; Whitespace when assessing their "visibility", to HEADER-P.
  ;;
  ;; HEADER-P can thus realize that no Header Record follows.
  ;;
  (or (typep #\Space header-type)
      (let* ((truncated (truncated-p record))
	     (line (if truncated (second record) record)))
	(plusp (length line)))
      ))

(defun HEADER-P (header-type record)
  "Does this record provide interesting context?"
  (let* ((truncated (truncated-p record))
	 (line (if truncated (second record) record)))
    (when (plusp (length line))
      (typep (char line 0) header-type))
    ))

(defun INITIAL-HEADER (header-type-pair sequence-pair)
  "Determine whether each of the two subsequences present their own headers."
  (let ((a-header-type (car header-type-pair))
        (b-header-type (cdr header-type-pair))
        (a-records (car sequence-pair))
        (b-records (cdr sequence-pair))) 
    (flet ((A-VISIBLE-P (record)
	     "Is this a visible A-FILE record?"
	     (visible-p a-header-type record))
	   (B-VISIBLE-P (record)
	     "Is this a visible B-FILE record?"
             (visible-p b-header-type record)))

      (let* ((a-visible (find-if #'a-visible-p a-records))
	     (b-visible (find-if #'b-visible-p b-records))
	     (a-header-p (when a-visible (header-p a-header-type a-visible)))
	     (b-header-p (when b-visible (header-p b-header-type b-visible))))
	;;
	;; For Empty Record Intervals, the cue to search for a
	;; Preceeding Header is taken from the opposite "side".
	;;
	(cons (if (nonep a-records) b-header-p a-header-p)
	      (if (nonep b-records) a-header-p b-header-p))
	))
    ))

(defun FIND-HEADER (header-type-pair sequence-pair interval-pair)
  "Return the most recent header(s), from both sides."
  (declare (values header-seq-pair headerval-pair))
  (let ((a-context (car sequence-pair))
	(b-context (cdr sequence-pair))
	(a-interval (car interval-pair))
	(b-interval (cdr interval-pair))
	(a-headerval ())
	(b-headerval ())
	(a-headers ())
	(b-headers ()))
    (flet ((A-INTERESTING-P (record)
	     "Is this an header record within A-FILE?"
	     (header-p (car header-type-pair) record))
	   (B-INTERESTING-P (record)
	     "Is this an header record within B-FILE?"
	     (header-p (cdr header-type-pair) record)))
      (let ((a-offset (position-if #'a-interesting-p a-context :from-end t))
	    (b-offset (position-if #'b-interesting-p b-context :from-end t)))
	(when a-offset
	  (let* ((a-start (first a-interval))
		 (a-position (+ a-start a-offset)))
	    (setq a-headerval (list a-position (1+ a-position))))
	  (setq a-headers (subseq a-context a-offset (1+ a-offset))))

	(when b-offset
	  (let* ((b-start (first b-interval))
		 (b-position (+ b-start b-offset)))
	    (setq b-headerval (list b-position (1+ b-position))))
	  (setq b-headers (subseq b-context b-offset (1+ b-offset))))
	))

    (values (cons a-headers b-headers)
	    (cons a-headerval b-headerval))
    ))

;;;
;;; NOTE:  The enclosed "diagnostic" terms impose a chronological
;;; sense on the two input sequences, where A-SEQUENCE is assumed
;;; to present some previous "version" of a subsequent B-SEQUENCE.
;;;
(defun DIAGNOSE-PAIR (differ-p sequence-pair)
  "Diagnose this pair, assuming a chronological sense."
  (let ((a-nonep (nonep (car sequence-pair)))
        (b-nonep (nonep (cdr sequence-pair))))
    (if differ-p
	(if a-nonep
	    (if b-nonep 'voided 'insert)
	    (if b-nonep 'delete 'modify))
	'common)))

(defun INTERVAL-TO-STRING (interval)
  "Convert an interval into a string."
  (declare (special *interval-format*))
  (when interval
    (let ((interval-start (first interval))
          (interval-end (second interval)))
      (format nil
	      *interval-format*
              interval-start
              (when (< interval-start interval-end)
                (1- interval-end)))
      )))

(defun CENTER-FILL (center-sequence
                    fill-count
                    &optional
                    (fill-item #\Space)
		    &rest keys)
  "Return the specified sequence centered within a filled field, as a string."
  (declare (values string start end))
  (let* ((center-string (coerce center-sequence 'string))
	 (center-length (length center-string))
         (fill #-symbolics
	       (make-string fill-count :initial-element fill-item)
	       #+symbolics
	       (make-string fill-count
			    :initial-element fill-item
			    :element-type (array-element-type center-string))))
    (multiple-value-bind (fill-start fill-end crop-start crop-end)
	(apply #'center-values center-length fill-count keys)
      (setf (subseq fill fill-start)
	    (subseq center-string crop-start crop-end))
      (values fill fill-start fill-end)
      )))

(defun CENTER-VALUES (center-length
		      fill-count
		      &key
		      (fill-minimum 2)
		      (right-crop nil))
  "Return a list of values for centering the sequence within a filled field."
  (declare (values fill-start fill-end crop-start crop-end))
  (let* ((fill-limit (min fill-count fill-minimum))
	 (center-limit (- fill-count fill-limit))
         (center-width (min center-limit center-length))
	 (center-extra (- center-limit center-width)))
    (multiple-value-bind (left-minimum left-extra crop-start crop-end)
	(if right-crop
	    (values (floor fill-limit 2)
		    (ceiling center-extra 2)
		    0
		    center-width)
	    (values (ceiling fill-limit 2)
		    (floor center-extra 2)
		    (- center-length center-width)
		    center-length))
      (let* ((fill-start (+ left-minimum left-extra))
	     (fill-end (+ fill-start center-width)))
	(values fill-start fill-end crop-start crop-end)
	))
    ))

(defun FRAME-RECORDS (records
                      &key
		      (change-bar "" change-bar-sp)
		      (tab-spaces nil tab-spaces-sp)
                      (width nil width-sp))
  "Frame each record, within any specific width."
  (declare (special *compare-framer*))
  (cond ((and change-bar-sp width-sp)
	 (let* ((change-string (string change-bar))
		(change-end  (min width (length change-string)))
		(frame-width (- width change-end))
		(frame-keys (list* :width frame-width
				   (when tab-spaces-sp
				     (list :tab-spaces tab-spaces))
				   )))
	   (map (sequence-type-of records)
		#'(lambda (record) (apply *compare-framer* record frame-keys))
		records)))
	((or change-bar-sp tab-spaces-sp width-sp)
	 (let ((frame-keys (nconc (when width-sp
				    (list :width width))
				  (when tab-spaces-sp
				    (list :tab-spaces tab-spaces))
				  )))
	   (map (sequence-type-of records)
		#'(lambda (record) (apply *compare-framer* record frame-keys))
		records)))
	(t records)))

(defun FRAME-RECORD (record &rest keys)
  "Expand Tabs for a record, within any specific width."
  (let* ((truncated (truncated-p record))
	 (line (if truncated (second record) record))
	 (line-type (if (or (characterp line)
			    (pathnamep line)
			    (symbolp line))
			(type-of line) (sequence-type-of line)))
	 (expansion (if (pathnamep line)
			(namestring line) (string line))
		    ))

    (setq expansion (apply #'expand-tabs expansion keys))

    ;;
    ;; NOTE: Records lose any truncation, when "framed".
    ;;
    (cond ((pathnamep line) (pathname expansion))
	  ;; Admit SYMBOL too.
	  ((symbolp line) (intern expansion))
	  (t (coerce expansion line-type)))
    ))

;;;
;;; NOTE! EXPAND-TABS (and thus its callers) would formerly perform
;;;	  insertion of CHANGE-BAR and record truncation with respect
;;;	  to WIDTH, where these were specified.
;;;
;;;	  This resulted in much unecessary record duplication, so these
;;;	  side-effects have been removed.  The caller must now output
;;;	  any CHANGE-BAR and confine its attention to within any WIDTH.
;;;
(defun EXPAND-TABS (tabbed-string
                    &key
                    (tab-spaces *default-tab-spaces*)
		    (width nil width-sp))
  "Expand Tabs into Spaces, according to Tab Stops, for the Tabbed String."
  (declare (special *default-tab-spaces*))
  ;;
  ;; TAB-SPACES is a (possibly circular) list of "relative displacements"
  ;; to each successive Tab Stop.  Every Tab will be replaced by the number
  ;; of Spaces required to indent the next TABBED-STRING character to the
  ;; column position immediately following the next available Tab Stop.
  ;;
  ;; As long as TAB-SPACES remain, each Tab is converted to the number
  ;; of Spaces necessary to satisfy the next relative displacement.
  ;;
  ;; Where no further Tab Stops remain, Tabs will simply be discarded.
  ;;
  (do ((string-length (length tabbed-string))
       (expansion-length nil)
       (expansion nil)
       (tab-found nil))
      ((or expansion (and expansion-length (not tab-found)))
       (or expansion tabbed-string))

    (when expansion-length
      (setq expansion
	    #-symbolics
	    ;;
	    ;; Avoid requiring an :ELEMENT-TYPE keyword implementation.
	    ;;
	    (make-string expansion-length :initial-element #\Space)
	    ;;
	    ;; Common Lisp now specifies that Element Type be CHARACTER,
	    ;; by default.  In this Tab Expansion case, SCL need comply.
	    ;;
	    #+symbolics
	    (make-string expansion-length
			 :initial-element #\Space
			 :element-type (array-element-type tabbed-string))))

    (let ((column-index 0)
	  (last-stop-remains tab-spaces)
	  (last-stop-index 0))
      (do ((string-index 0 (1+ string-index)))
	  ((or (and width-sp (>= column-index width))
	       (= string-index string-length))
	   (setq expansion-length column-index))
	(let ((string-char (char tabbed-string string-index)))
	  (if (char-equal string-char #\Tab)
	      (progn
		(setq tab-found t)

		(do ((next-stop-remains last-stop-remains
					(rest next-stop-remains))
		     (next-stop-index last-stop-index))
		    ((or (< column-index next-stop-index)
			 (and width-sp (= next-stop-index width))
			 (endp next-stop-remains))
		     (setq last-stop-remains next-stop-remains
			   last-stop-index next-stop-index))
		  (let ((next-stop (first next-stop-remains)))
		    (if width-sp
			(setq next-stop-index
			      (min (+ next-stop-index next-stop) width))
			(incf next-stop-index next-stop))
		    ))
		  
		(let ((space-count (- last-stop-index column-index)))
		  (when (plusp space-count)
		    (incf column-index space-count))
		  ))
	      (progn
		(when expansion
		  (setf (schar expansion column-index) string-char))
		(incf column-index)
		)))
	))
    ))

(defun PURE-STRING (minimum-length char &optional (symbol nil symbol-sp))
  "Get or Make a Read Only String containing the specified character."
  (declare (special *default-width*))
  (let* ((pure-symbol (if symbol-sp
			  symbol
			  (ecase char		; Catch unregistered Strings.
			    (#\< 'pure-less)
			    (#\> 'pure-greater)
			    (#\= 'pure-equal)
			    (#\- 'pure-minus)
			    (#\Space 'pure-space))
			  ))
	 (maximum-string
	   (and (boundp pure-symbol) (symbol-value pure-symbol)))
	 (maximum-length
	   (when (stringp maximum-string) (length maximum-string))))
    (when (or (null maximum-length) (> minimum-length maximum-length))
      (let ((next-length (max minimum-length *default-width*)))
	(setq maximum-string (make-string next-length :initial-element char))
	(when pure-symbol (set pure-symbol maximum-string))
	))
    ;;
    ;; NOTE! The caller is expected to confine its attention
    ;;       to within the specified MINIMUM-LENGTH.
    ;;
    maximum-string))

;;;
;;; Suspend Module Context:
;;;
