;;; -*- Mode: LISP; Syntax: Common-Lisp; Package: COMPARE; Base: 10 -*-
;;;
;;; Source: compare-face.lisp	Module: compare		Status:	operational
;;;
;;; History:	Please record your edits in "compare-history.text".
;;;
;;; Purpose:	Define the SEQUENCE COMPARISON utility's interfaces,
;;;		and implement its central algorithm.
;;;
;;; Usage:	This file is intended to be portable
;;;		to any COMMON LISP Environment.
;;;
;;; Compile:	Cf. "compare:compare;compare.lisp"
;;;
;;; Contents:
;;;
;;;	The following functions implement an efficient algorithm for
;;;	finding the longest subsequence common to two input sequences.
;;;	In this context, "subsequence" refers not only to contiguous
;;;	subsequences (as obtained via the SUBSEQ operation) but to any
;;;	(possibly discontiguous) sequentially ordered set of elements.
;;;
;;;	The running time is O((r + s) log s), where r is the number
;;;	of ordered pairs of positions where the two sequences match,
;;;	and s is the maximum of (m and n) the two input sequence lengths.
;;;
;;;	Performance will therefore be O(s^2 log s) in the worst case,
;;;	but is O(s log s) where most positions of one sequence match
;;;	relatively few positions in the other.
;;;
;;; Notes:
;;;
;;;	This module wraps interfaces around the central algorithm at
;;;	four higher levels: File, Stream, Subsequence, and Position
;;;	Interval.  The final, lowest exported level will return sequence
;;;	element position intervals instead of the subsequences themselves.
;;;
;;;	Pairs of such intervals which specify apparent modifications
;;;	(or "corresponding" pairs of differing subsequences) give rise to
;;;	the term "difference", where reference to these differing pairs of
;;;	subsequences is intended.  Differing subsequences may further be
;;;	classified as: Insertions, Modifications, or Deletions where it
;;;	makes sense to identify a first sequence as "prior" to the second.
;;;
;;;	At each level "correspondence" variants identify what two sequences
;;;	have IN COMMON, and "difference" variants identify their differences
;;;	(via "dotted pairs".)  The underlying COMPARE implementations realize
;;;	their CORRESPONDENCE function when passed NIL as "differ-p", and
;;;	they realize their DIFFERENCE function when passed a NON-NIL value.
;;;
;;;	At the File and Stream levels the sequences are assumed to consist
;;;	of records based on the type STRING.  Streams are considered to
;;;	have been truncated where their final record (before End Of File)
;;;	is not terminated by a Newline.  Records terminating prematurely
;;;	in this way are marked by replacing them with a list consisting of
;;;	the internal symbol "TRUNCATED" followed by their "untruncated" self.
;;;
;;; External Interfaces (generated by WRAP-INTERFACES, below:)
;;;
;;;	correspondence-files,
;;;	difference-files	a-file b-file &key output-file
;;;				format width affix transfix prefix suffix
;;;				ignore-case-and-style ignore-whitespace
;;;
;;;	correspondence-streams,
;;;	difference-streams	a-stream b-stream &key output-stream
;;;				format width affix transfix prefix suffix
;;;				ignore-case-and-style ignore-whitespace
;;;
;;;	correspondence-sequences,
;;;	difference-sequences	a-sequence b-sequence
;;;				&key affix transfix prefix suffix
;;;				ignore-case-and-style ignore-whitespace
;;;
;;;	correspondence-intervals,
;;;	difference-intervals	a-sequence b-sequence
;;;				&key affix transfix prefix suffix
;;;				ignore-case-and-style ignore-whitespace
;;;
;;;	common-sequence		a-sequence b-sequence &key
;;;				ignore-case-and-style ignore-whitespace
;;;
;;;	common-pairs		a-sequence b-sequence &key method
;;;				ignore-case-and-style ignore-whitespace
;;;
;;; "Wrapped" Local Interfaces:
;;;
;;;	compare-files		differ-p a-file b-file &key output-file
;;;				format width affix transfix prefix suffix
;;;				ignore-case-and-style ignore-whitespace
;;;
;;;	compare-streams		differ-p a-stream b-stream &key output-stream
;;;				format width affix transfix prefix suffix
;;;				ignore-case-and-style ignore-whitespace
;;;
;;;	compare-sequences	differ-p a-sequence b-sequence
;;;				&key affix transfix prefix suffix
;;;				ignore-case-and-style ignore-whitespace
;;;
;;;	compare-intervals	differ-p a-sequence b-sequence
;;;				&key affix transfix prefix suffix
;;;				ignore-case-and-style ignore-whitespace
;;;
;;; NOTE!  Please consult "compare-body.lisp" for the central algorithm's
;;;	   implementation, and "compare-io.lisp" for various "application
;;;	   interfaces" enabling Users to override default I/O behaviour.
;;;
;;; Local Interfaces:
;;;
;;;	wrap-interfaces		compare-name correspondence-name difference-name
;;;
;;;	basic-compare-sequences	differ-p a-sequence b-sequence
;;;				&key affix transfix prefix suffix
;;;				ignore-case-and-style ignore-whitespace
;;;
;;;	common-intervals	a-sequence b-sequence &key
;;;				ignore-case-and-style ignore-whitespace
;;;
;;;	reverse-cons		cons
;;;

;;;
;;; Module Prologue:
;;;
(in-package compare)

;;; No Requirements.
;;; No Shadows.
;;; No Unusual Packages.
;;; Nothing to Import.

;;;
;;; The Primary Interfaces:
;;;
(export '(correspondence-files
	   difference-files
	   correspondence-streams
	   difference-streams
	   correspondence-sequences
	   difference-sequences
	   correspondence-intervals
	   difference-intervals
	   common-sequence
	   common-pairs
	   *default-compare-method*))

;;;
;;; Macros:
;;;
(defmacro WRAP-INTERFACES (compare-name correspondence-name difference-name)
  "Wrap correspondence and difference interfaces around their implementation."
  (let* ((doc-control "Apply ~A via its ~A interface.")
         (correspondence-doc
	   (format nil doc-control compare-name correspondence-name))
         (difference-doc
	   (format nil doc-control compare-name difference-name)))
    `(progn
       (defun ,correspondence-name (&rest args)
         ,correspondence-doc
         (apply #',compare-name nil args))
       
       (defun ,difference-name (&rest args)
         ,difference-doc
         (apply #',compare-name t args))
       )))

;;;
;;; "Wrapped" Interfaces:
;;;
(wrap-interfaces compare-files
                 CORRESPONDENCE-FILES DIFFERENCE-FILES)
(wrap-interfaces compare-streams
                 CORRESPONDENCE-STREAMS DIFFERENCE-STREAMS)
(wrap-interfaces compare-sequences
                 CORRESPONDENCE-SEQUENCES DIFFERENCE-SEQUENCES)
(wrap-interfaces compare-intervals
                 CORRESPONDENCE-INTERVALS DIFFERENCE-INTERVALS)

;;;
;;; Special Variables and Constants:
;;;
(defparameter *RECORD-READER* 'read-records
  "The Standard Record Reader")

(defparameter *DEFAULT-COMPARE-METHOD* :any
  "The Default Compare Method")

;;;
;;; Now for the Code:
;;;
(defun COMPARE-FILES (differ-p a-file b-file
		      &rest keys
		      &key output-file
		      &allow-other-keys)
  "Send the result of comparing two files to a third, output file."
  (with-open-file (a-stream a-file)
    (with-open-file (b-stream b-file)
      (if output-file
	  (with-open-file (output-stream output-file :direction :output)
	    (apply #'compare-streams differ-p a-stream b-stream
		   :output-stream output-stream keys))
	  (apply #'compare-streams differ-p a-stream b-stream keys))
      )))

(defun COMPARE-STREAMS (differ-p a-stream b-stream &rest keys)
  "Present the result of comparing two streams via a Compare Formatter."
  (declare (special *record-reader* *compare-formatter*))
  (let ((a-sequence (funcall *record-reader* a-stream))
        (b-sequence (funcall *record-reader* b-stream))
        (source-pair (cons a-stream b-stream)))
    
    (apply *compare-formatter*
           differ-p
           a-sequence
           b-sequence
           :source-pair source-pair		; Pass along the Sources.
           keys)))

(defun COMMON-SEQUENCE (a-sequence b-sequence
			&rest keys
			&key
			(verify-matches nil)	; Turn ON during testing.
			&allow-other-keys)
  "Return the subsequence two sequences have in common."
  (let* ((interval-pairs (apply #'common-intervals a-sequence b-sequence keys))
         (subseq-pairs (subseq-intervals a-sequence b-sequence interval-pairs))
         (a-sequence-type (sequence-type-of a-sequence))
         (b-sequence-type (sequence-type-of b-sequence))
         (c-sequence-type (if (eq a-sequence-type b-sequence-type)
			      b-sequence-type 'list))
         (c-null-subseq (coerce nil c-sequence-type)))
    
    (reduce
      #'(lambda (subseq-pair c-subseq-reduction)
	  (let ((a-subseq (car subseq-pair))
		(b-subseq (cdr subseq-pair))
		(c-subseq c-null-subseq))
	    (if (or (not verify-matches)
		    (and
		      (let ((a-length (length a-subseq))
			    (b-length (length b-subseq)))
			(= a-length b-length))	; Verify thoroughly.
		      (flet ((EQUIVALENT (a-element b-element)
			       (declare (special *compare-normalizer*))
			       "Test normalized element pairs for equality."
			       (equal
				 (apply *compare-normalizer* a-element keys)
				 (apply *compare-normalizer* b-element keys))
			       ))
			(every #'equivalent a-subseq b-subseq))
		      ))
		(setq c-subseq b-subseq)	; Return the "newer" sequence.
		(warn "Erroneous Match: ~S and ~S~%" a-subseq b-subseq))
	    (concatenate c-sequence-type c-subseq c-subseq-reduction)))
      subseq-pairs
      :initial-value c-null-subseq
      ;;
      ;; The point of associating from the right (end) is that it limits
      ;; any obvious implementation of CONCATENATE to scanning for ends
      ;; of each common subsequence element, rather than requiring it to
      ;; skip each previously concatenated element as the reduction grows.
      ;;
      :from-end t)
    ))

;;;
;;; The following jacket routine "protects" the internally maintained,
;;; multiple value, BASIC-COMPARE-SEQUENCES interface from external access.
;;;
(defun COMPARE-SEQUENCES (&rest args)
  "Return the result of comparing two sequences as a third, output sequence."
  (values (apply #'basic-compare-sequences args)))

(defun BASIC-COMPARE-SEQUENCES (differ-p a-sequence b-sequence &rest keys)
  "Return the various results of comparing two sequences."
  (declare (values sequence-pairs interval-pairs length-pair))
  (multiple-value-bind (interval-pairs length-pair)
      (apply #'compare-intervals differ-p a-sequence b-sequence keys)
    (values (subseq-intervals a-sequence b-sequence interval-pairs)
            interval-pairs
            length-pair)))

(defun COMPARE-INTERVALS (differ-p a-sequence b-sequence
			  &rest keys
			  &key
			  (affix nil affix-sp)
			  (transfix nil transfix-sp)
			  (prefix 0 prefix-sp)
			  (suffix 0 suffix-sp)
			  &allow-other-keys)
  "Compare two sequences returning interval sequence pairs and a length pair."
  (multiple-value-bind (interval-pairs length-pair)
      (apply #'common-intervals a-sequence b-sequence keys)
    (when differ-p
      (setq interval-pairs (complement-intervals interval-pairs length-pair)))
    
    (when affix-sp
      (if (integerp affix)
	  (progn
	    (unless transfix-sp (setq transfix (max affix 0)))
	    (unless prefix-sp (setq prefix (ceiling affix 2)))
	    (unless suffix-sp (setq suffix (floor affix 2))))
	  (cerror "No \"affix default\" will apply."
		  "The ~S keyword specifies a non-integral value: ~D."
		  :affix affix)
	  ))
    
    (when transfix
      (if  (and (integerp transfix) (not (minusp transfix)))
	   (setq interval-pairs (fasten-intervals interval-pairs
						  length-pair
						  :transfix transfix))
	   (cerror "No \"transfixion\" will apply."
		   "The ~S keyword specifies a ~A value: ~D."
		   :transfix
		   (if (integerp transfix) "negative" "non-integral")
		   transfix)
	   ))
    
    (if (and (integerp prefix) (integerp suffix))
	(unless (and (zerop prefix) (zerop suffix))
	  (setq interval-pairs (affix-intervals interval-pairs
						length-pair
						:prefix prefix
						:suffix suffix)))
	(multiple-value-bind
	  (keyword value)
	    (cond ((not (integerp prefix)) (values :prefix prefix))
		  ((not (integerp suffix)) (values :suffix suffix)))
	  (cerror "Neither prefix nor suffix will apply."
		  "The ~S keyword specifies a non-integral value: ~D."
		  keyword value)
	  ))
    
    (values interval-pairs length-pair)))

(defun COMMON-INTERVALS (a-sequence b-sequence &rest keys)
  "Return the common interval sequence, of corresponding subsequence pairs."
  (multiple-value-bind (common-pairs length-pair)
      (apply #'common-pairs a-sequence b-sequence keys)
    (values (interval-pairs common-pairs) length-pair)
    ))

(defun REVERSE-CONS (cons)
  "CONS both parts of another CONS, in reverse."
  (cons (cdr cons) (car cons)))

;;;
;;; The following jacket function for BASIC-COMMON-PAIRS
;;; provides limited capability for performance diagnosis.
;;;
(defun COMMON-PAIRS (a-sequence b-sequence
		     &rest keys
		     &key
		     (method *default-compare-method*)
		     (time-method nil)
		     (analyze-method nil)
		     (symmetry nil)
		     &allow-other-keys)
  "Match the element pairs for a Longest Common Subsequence, efficiently."
  (declare (special *default-compare-method*))
  (let ((comparitor (ccase method
		      ((:any :lcs) #'basic-common-pairs)
		      (:scan #'scan-common-pairs))
		    ))
    (flet ((COMMON-PAIRS-1 (&rest args)
	     "Time BASIC-COMMON-PAIRS, as requested."
	     (when analyze-method
	       (format t "~&[Logging Pairs.]~%"))
	     (multiple-value-bind (matched-pairs length-pair lcs-length
				   pair-count work-count work-done)
		 (if time-method
		     (time (apply comparitor args)) (apply comparitor args))
	       (when analyze-method
		 (let* ((use-percent
			  (if (zerop pair-count)
			      100. (/ (* 100. lcs-length) pair-count)
			      ))
			(a-length (car length-pair))
			(b-length (cdr length-pair))
			(work-maximum (* a-length b-length))
			(work-percent
			  (if (zerop work-maximum)
			      100. (/ (* 100. work-count) work-maximum)
			      )))
		   (format t
			   "~&[~@[~A ~]~
			    ~D/~D (~,1F%) of the Possible Pairs.]~%"
			   (when work-done (string-capitalize work-done))
			   work-count
			   work-maximum
			   work-percent)

		   (format t
			   "~&[Common Subsequence used ~
			    ~D/~D (~,1F%) of the Pairs Logged.]~%"
			   lcs-length
			   pair-count
			   use-percent)
		   ))
	       (values matched-pairs length-pair))
	     ))

      (let* ((a-length (length a-sequence))
	     (b-length (length b-sequence))
	     (flip (and symmetry (not (funcall symmetry a-length b-length)))
		   ))
	(multiple-value-bind (i-sequence j-sequence)
	    (if flip
		(values b-sequence a-sequence)
		(values a-sequence b-sequence))
	  (multiple-value-bind (matched-pairs length-pair)
	      (apply #'common-pairs-1 i-sequence j-sequence keys)
	    (if flip
		(values (mapcar #'reverse-cons matched-pairs)
			(reverse-cons length-pair))
		(values matched-pairs length-pair))
	    ))
	))
    ))

;;;
;;; Suspend Module Context:
;;;
